/** Tarot Major Arcana (22) — `name` İngilizce, API / prompt için sabit; gösterim `t("tarot.cN")` */
export const TAROT_CARDS = [
  { id: 0, name: 'The Fool', emoji: '🃏' },
  { id: 1, name: 'The Magician', emoji: '🎩' },
  { id: 2, name: 'The High Priestess', emoji: '👸' },
  { id: 3, name: 'The Empress', emoji: '👑' },
  { id: 4, name: 'The Emperor', emoji: '🤴' },
  { id: 5, name: 'The Hierophant', emoji: '⛪' },
  { id: 6, name: 'The Lovers', emoji: '💑' },
  { id: 7, name: 'The Chariot', emoji: '🏇' },
  { id: 8, name: 'Strength', emoji: '💪' },
  { id: 9, name: 'The Hermit', emoji: '🧙' },
  { id: 10, name: 'Wheel of Fortune', emoji: '🎡' },
  { id: 11, name: 'Justice', emoji: '⚖️' },
  { id: 12, name: 'The Hanged Man', emoji: '🙃' },
  { id: 13, name: 'Death', emoji: '💀' },
  { id: 14, name: 'Temperance', emoji: '☯️' },
  { id: 15, name: 'The Devil', emoji: '😈' },
  { id: 16, name: 'The Tower', emoji: '🗼' },
  { id: 17, name: 'The Star', emoji: '⭐' },
  { id: 18, name: 'The Moon', emoji: '🌙' },
  { id: 19, name: 'The Sun', emoji: '☀️' },
  { id: 20, name: 'Judgement', emoji: '⚡' },
  { id: 21, name: 'The World', emoji: '🌍' },
];

export const FALCI_NAMES = [
  'Zeynep',
  'Ayşe',
  'Fatma',
  'Emine',
  'Hatice',
  'Elif',
  'Meryem',
  'Zehra',
  'Esma',
  'Hanife',
];
