import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  keyboardAvoid: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    fontSize: 28,
    fontWeight: '400',
  },
  coinBadgeLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 5,
  },
  coinBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 5,
  },
  coinIcon: {
    fontSize: 18,
  },
  coinText: {
    fontSize: 16,
    fontWeight: '700',
  },
  logoText: {
    fontSize: 28,
    fontWeight: '800',
    fontStyle: 'italic',
    letterSpacing: -0.5,
  },
  profileIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileEmoji: {
    fontSize: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 24,
    textAlign: 'center',
  },
  fortuneTypesContainer: {
    gap: 16,
    paddingHorizontal: 0,
  },
  fortuneTypeCard: {
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 0,
  },
  fortuneTypeImage: {
    height: 200,
    width: '100%',
    justifyContent: 'center',
  },
  fortuneTypeImageStyle: {
    borderRadius: 20,
  },
  fortuneTypeOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  fortuneTypeEmoji: {
    fontSize: 56,
    marginBottom: 12,
  },
  fortuneTypeTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  fortuneTypeDesc: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
    opacity: 0.9,
    textAlign: 'center',
  },
  chatMessages: {
    paddingVertical: 16,
    paddingHorizontal: 4,
    minHeight: 120,
  },
  chatBubbleWrap: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingHorizontal: 8,
    width: '100%',
  },
  chatBubbleUser: {
    justifyContent: 'flex-end',
  },
  chatBubble: {
    maxWidth: '85%',
    padding: 14,
    borderRadius: 18,
  },
  chatBubbleLeft: {
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
  },
  chatBubbleRight: {
    alignSelf: 'flex-end',
    borderBottomRightRadius: 4,
  },
  chatText: {
    fontSize: 15,
    lineHeight: 22,
  },
  chatImages: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  chatThumb: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  chatMore: {
    fontSize: 12,
    alignSelf: 'center',
  },
  chatCardsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  chatCardBubble: {
    padding: 8,
    borderRadius: 10,
    alignItems: 'center',
    minWidth: 70,
  },
  chatCardEmoji: { fontSize: 24, marginBottom: 4 },
  chatCardName: { fontSize: 11, fontWeight: '700', textAlign: 'center' },
  chatCardPos: { fontSize: 10 },
  chatInputArea: {
    padding: 16,
    borderRadius: 20,
    marginTop: 8,
  },
  chatActions: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
  },
  chatActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
  },
  chatActionIcon: { fontSize: 22 },
  chatActionText: { fontSize: 15, fontWeight: '700' },
  chatComposer: { gap: 12 },
  chatImageStrip: { marginBottom: 8, maxHeight: 90 },
  chatImageWrap: { position: 'relative', marginRight: 8 },
  chatComposerThumb: { width: 70, height: 70, borderRadius: 12 },
  chatRemoveImg: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#e74c3c',
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatRemoveIcon: { color: '#fff', fontSize: 12, fontWeight: '800' },
  chatAddImg: {
    width: 70,
    height: 70,
    borderRadius: 12,
    borderWidth: 2,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatAddIcon: { fontSize: 28 },
  chatSendBtn: {
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  chatSendText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  heroSection: {
    padding: 32,
    borderRadius: 20,
    alignItems: 'center',
    marginBottom: 24,
  },
  heroEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 15,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 22,
  },
  heroCTA: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  ctaButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
  },
  ctaPrimary: {
    backgroundColor: '#8B4513',
  },
  ctaSecondary: {

  },
  ctaIcon: {
    fontSize: 18,
  },
  ctaText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  features: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  featureCard: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  featureIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  featureTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 4,
  },
  featureText: {
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: 15,
  },
  dreamInputContainer: {
    padding: 20,
    borderRadius: 20,
    marginBottom: 24,
  },
  astroHubOuter: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  astroHubHero: {
    marginBottom: 22,
    paddingBottom: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  astroHubKicker: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 3,
    marginBottom: 8,
  },
  astroHubTitle: {
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 32,
    marginBottom: 10,
  },
  astroHubSubtitle: {
    fontSize: 15,
    lineHeight: 22,
  },
  astroModeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 18,
    marginBottom: 12,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  astroModeEmoji: {
    fontSize: 32,
    marginRight: 14,
  },
  astroModeTextCol: {
    flex: 1,
  },
  astroModeTitle: {
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  astroModeDesc: {
    fontSize: 13,
    lineHeight: 19,
  },
  astroModeChevron: {
    fontSize: 20,
    fontWeight: '600',
    marginLeft: 8,
  },
  astroComingEmoji: {
    fontSize: 48,
    textAlign: 'center',
    marginBottom: 12,
  },
  astroResultKicker: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 2,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  inputHint: {
    fontSize: 13,
    marginBottom: 16,
    opacity: 0.9,
  },
  astrologyLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginTop: 12,
    marginBottom: 6,
  },
  astrologyInput: {
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    borderWidth: 1,
  },
  astrologyPickerButton: {
    minHeight: 52,
    justifyContent: 'center',
  },
  astrologyPickerText: {
    fontSize: 16,
  },
  cityScroll: {
    marginVertical: 12,
    maxHeight: 50,
  },
  cityChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    marginRight: 10,
    borderWidth: 2,
  },
  cityChipText: {
    fontSize: 14,
    fontWeight: '600',
  },
  dreamInput: {
    borderRadius: 12,
    padding: 16,
    fontSize: 15,
    fontWeight: '500',
    minHeight: 160,
    borderWidth: 1,
    marginBottom: 16,
  },
  dreamButton: {
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dreamButtonText: {
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  dreamButtonCost: {
    fontSize: 13,
    fontWeight: '700',
    opacity: 0.9,
  },
  tarotContainer: {
    padding: 24,
    borderRadius: 20,
    marginBottom: 24,
  },
  tarotTitle: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  tarotSubtitle: {
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 32,
  },
  shuffleContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  shuffleEmoji: {
    fontSize: 80,
    marginBottom: 24,
  },
  shuffleButton: {
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
    minWidth: 200,
    alignItems: 'center',
  },
  shuffleButtonText: {
    fontSize: 17,
    fontWeight: '800',
  },
  cardsDisplay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 12,
  },
  tarotCard: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    minHeight: 160,
    justifyContent: 'center',
  },
  cardEmoji: {
    fontSize: 48,
    marginBottom: 12,
  },
  cardName: {
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
  },
  cardPosition: {
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  readButton: {
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  readButtonText: {
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  readButtonCost: {
    fontSize: 13,
    fontWeight: '700',
    opacity: 0.9,
  },
  reshuffleButton: {
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
  },
  reshuffleText: {
    fontSize: 15,
    fontWeight: '700',
  },
  selectedCardsContainer: {
    marginBottom: 20,
  },
  selectedTitle: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
  },
  selectedCardsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  selectedCard: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  selectedCardEmoji: {
    fontSize: 32,
    marginBottom: 6,
  },
  selectedCardName: {
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  selectedCardPos: {
    fontSize: 10,
    fontWeight: '600',
  },
  deckGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
    justifyContent: 'flex-start',
  },
  deckCard: {
    width: (width - 90) / 4,
    height: (width - 90) / 4 * 1.5,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    position: 'relative',
    marginBottom: 4,
  },
  deckCardEmoji: {
    fontSize: 28,
  },
  checkMark: {
    position: 'absolute',
    top: 4,
    right: 4,
    fontSize: 16,
    fontWeight: '900',
  },
  // Deck Animation Styles
  deckContainer: {
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 16,
  },
  deckInfo: {
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 24,
    textAlign: 'center',
  },
  cardStack: {
    width: 200,
    height: 280,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stackedCard: {
    position: 'absolute',
    width: 180,
    height: 260,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#ccc',
  },
  stackedCard2: {
    bottom: 8,
    left: 8,
    transform: [{ rotate: '-2deg' }],
  },
  stackedCard3: {
    bottom: 16,
    left: 16,
    transform: [{ rotate: '-4deg' }],
  },
  topCard: {
    width: 180,
    height: 260,
    borderRadius: 16,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  topCardIcon: {
    fontSize: 80,
    marginBottom: 12,
  },
  topCardText: {
    fontSize: 18,
    fontWeight: '600',
  },
  deckCount: {
    fontSize: 14,
    marginTop: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 14,
  },
  section: {
    padding: 20,
    borderRadius: 24,
    borderWidth: 2,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionBadge: {
    fontSize: 15,
    fontWeight: '700',
  },
  imagesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  imageCard: {
    width: (width - 80) / 3,
    height: (width - 80) / 3,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
  },
  imagePreview: {
    width: '100%',
    height: '100%',
  },
  removeButton: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: '#e74c3c',
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeIcon: {
    color: 'white',
    fontSize: 16,
    fontWeight: '800',
  },
  addImageCard: {
    width: (width - 80) / 3,
    height: (width - 80) / 3,
    borderRadius: 16,
    borderWidth: 3,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addIcon: {
    fontSize: 36,
    fontWeight: '300',
  },
  fortuneButton: {
    marginTop: 20,
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fortuneButtonText: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  fortuneButtonCost: {
    fontSize: 13,
    fontWeight: '700',
    opacity: 0.9,
  },
  fortuneCard: {
    padding: 24,
    borderRadius: 24,
    borderWidth: 2,
  },
  fortuneHeader: {
    marginBottom: 20,
  },
  fortuneTitle: {
    fontSize: 24,
    fontWeight: '900',
  },
  fortuneText: {
    fontSize: 16,
    lineHeight: 26,
    fontWeight: '500',
    marginBottom: 24,
  },
  followUpRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
  },
  followUpInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 100,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 16,
  },
  followUpSend: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    justifyContent: 'center',
    minHeight: 44,
  },
  followUpSendText: {
    fontSize: 15,
    fontWeight: '700',
  },
  newFortuneButton: {
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  newFortuneButtonText: {
    fontSize: 17,
    fontWeight: '800',
  },
  infoSection: {
    padding: 24,
    borderRadius: 24,
    borderWidth: 2,
  },
  infoTitle: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 20,
  },
  steps: {
    gap: 16,
  },
  stepCard: {
    alignItems: 'center',
    gap: 8,
  },
  floatingThemeButton: {
    position: 'absolute',
    bottom: 24,
    left: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  themeButtonIcon: {
    fontSize: 28,
  },
});
